services:
  backend:
    image: navamsharma142/backend:latest
    container_name: film-rental-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN}
    ports:
      - "8080:8080"
